

#pragma once
//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------

namespace Windows {
    namespace UI {
        namespace Xaml {
            namespace Controls {
                ref class Grid;
                ref class TextBlock;
                ref class FlipView;
                ref class RichTextBlock;
            }
        }
    }
}

namespace JPG_Spinner
{
    partial ref class ExplanationProgressive : public ::Windows::UI::Xaml::Controls::Page, 
        public ::Windows::UI::Xaml::Markup::IComponentConnector
    {
    public:
        void InitializeComponent();
        virtual void Connect(int connectionId, ::Platform::Object^ target);
    
    private:
        bool _contentLoaded;
    
        private: ::Windows::UI::Xaml::Controls::Grid^ LayoutRoot;
        private: ::Windows::UI::Xaml::Controls::Grid^ Input;
        private: ::Windows::UI::Xaml::Controls::Grid^ Output;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ TextBlock4;
        private: ::Windows::UI::Xaml::Controls::FlipView^ FlipView1;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ TextBlock2;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ TextBlock3;
        private: ::Windows::UI::Xaml::Controls::RichTextBlock^ TextBlock1;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ ExplanationProgressiveHeader;
    };
}

