

#pragma once
//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------

namespace Windows {
    namespace UI {
        namespace Xaml {
            namespace Controls {
                ref class Grid;
                ref class Image;
                ref class TextBlock;
            }
        }
    }
}
namespace Windows {
    namespace UI {
        namespace Xaml {
            namespace Shapes {
                ref class Rectangle;
            }
        }
    }
}

namespace JPG_Spinner
{
    partial ref class ExplanationCrop : public ::Windows::UI::Xaml::Controls::Page, 
        public ::Windows::UI::Xaml::Markup::IComponentConnector
    {
    public:
        void InitializeComponent();
        virtual void Connect(int connectionId, ::Platform::Object^ target);
    
    private:
        bool _contentLoaded;
    
        private: ::Windows::UI::Xaml::Controls::Grid^ LayoutRoot;
        private: ::Windows::UI::Xaml::Controls::Grid^ Input;
        private: ::Windows::UI::Xaml::Controls::Grid^ Output;
        private: ::Windows::UI::Xaml::Shapes::Rectangle^ RectVertical3;
        private: ::Windows::UI::Xaml::Shapes::Rectangle^ RectHorizontal3;
        private: ::Windows::UI::Xaml::Shapes::Rectangle^ RectVertical2;
        private: ::Windows::UI::Xaml::Shapes::Rectangle^ RectHorizontal2;
        private: ::Windows::UI::Xaml::Shapes::Rectangle^ RectVertical;
        private: ::Windows::UI::Xaml::Shapes::Rectangle^ RectHorizontal;
        private: ::Windows::UI::Xaml::Controls::Image^ Image1;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ TextBlock1;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ ExplanationCropHeader;
    };
}

