

#pragma once
//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------

namespace Windows {
    namespace UI {
        namespace Xaml {
            namespace Controls {
                ref class Grid;
                ref class Image;
                ref class UserControl;
                ref class TextBlock;
            }
        }
    }
}
namespace Windows {
    namespace UI {
        namespace Xaml {
            ref class VisualStateGroup;
            ref class VisualState;
        }
    }
}

namespace JPG_Spinner
{
    partial ref class ExplanationProgressive : public ::Windows::UI::Xaml::Controls::Page, 
        public ::Windows::UI::Xaml::Markup::IComponentConnector
    {
    public:
        void InitializeComponent();
        virtual void Connect(int connectionId, ::Platform::Object^ target);
    
    private:
        bool _contentLoaded;
    
        private: ::Windows::UI::Xaml::Controls::Grid^ LayoutRoot;
        private: ::Windows::UI::Xaml::Controls::Grid^ Input;
        private: ::Windows::UI::Xaml::Controls::Grid^ Output;
        private: ::Windows::UI::Xaml::Controls::Image^ DisplayImage;
        private: ::Windows::UI::Xaml::Controls::UserControl^ ButtonLeft;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ TextBlockProgressive;
        private: ::Windows::UI::Xaml::Controls::UserControl^ ButtonRight;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ TextBlock2;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ ButtonRightTextBlock;
        private: ::Windows::UI::Xaml::VisualStateGroup^ CommonStatesRight;
        private: ::Windows::UI::Xaml::VisualState^ NormalRight;
        private: ::Windows::UI::Xaml::VisualState^ PointerOverRight;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ ButtonLeftTextBlock;
        private: ::Windows::UI::Xaml::VisualStateGroup^ CommonStatesLeft;
        private: ::Windows::UI::Xaml::VisualState^ NormalLeft;
        private: ::Windows::UI::Xaml::VisualState^ PointerOverLeft;
        private: ::Windows::UI::Xaml::Controls::Image^ Image1;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ TextBlock1;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ InputTextBlock1;
    };
}

