

#pragma once
//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------

namespace Windows {
    namespace UI {
        namespace Xaml {
            namespace Controls {
                ref class TextBlock;
            }
        }
    }
}
namespace Windows {
    namespace UI {
        namespace Xaml {
            namespace Documents {
                ref class Paragraph;
                ref class Hyperlink;
            }
        }
    }
}

namespace JPG_Spinner
{
    partial ref class SettingsPrivacyPolicy : public ::Windows::UI::Xaml::Controls::SettingsFlyout, 
        public ::Windows::UI::Xaml::Markup::IComponentConnector
    {
    public:
        void InitializeComponent();
        virtual void Connect(int connectionId, ::Platform::Object^ target);
    
    private:
        bool _contentLoaded;
    
        private: ::Windows::UI::Xaml::Controls::TextBlock^ PrivacyPolicyDate;
        private: ::Windows::UI::Xaml::Documents::Paragraph^ PrivacyPolicyParagraph1;
        private: ::Windows::UI::Xaml::Documents::Paragraph^ PrivacyPolicyParagraph2;
        private: ::Windows::UI::Xaml::Documents::Paragraph^ PrivacyPolicyParagraph3;
        private: ::Windows::UI::Xaml::Documents::Paragraph^ PrivacyPolicyParagraph4;
        private: ::Windows::UI::Xaml::Documents::Hyperlink^ HyperlinkAnalyzingCrashReports;
        private: ::Windows::UI::Xaml::Documents::Hyperlink^ HyperlinkPrivacyPolicy;
    };
}

